# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1e346c0a787cbaf2c47005eb22e263465e496a8abb68c963a0e47f30ddf536a19ab7bea8d4984b773c73a8f131a6e0808787b3426b603f562cd9ce94787fe35

test:
  secret_key_base: 8981cd99c4200a557d97e0861fdf232403359734ba756398ab0d858b93f74dc8d3412717fda563faec8c645d5bc60124e483f3598f247ae9abf9b64233be06fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
